#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import rospy
from geometry_msgs.msg import Quaternion


# Inicializar el nodo
rospy.init_node('nodo_suscriptor_quat')

# Función de callback
def callback_func(msg):
    print("Cuaternion leido: w={}, x={}, y={}, z={}".format(msg.w, msg.x, msg.y, msg.z))

# Declaración del suscriptor
topic = 'topic_quat'
pub = rospy.Subscriber(topic, Quaternion, callback_func)

# Mantener el nodo activo (hasta que se detenga
rospy.spin()

