#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import rospy
from geometry_msgs.msg import Pose


# Inicializar el nodo
rospy.init_node('nodo_suscriptor_pose')

# Función de callback
def callback_func(msg):
    p = msg.position
    q = msg.orientation
    print("\nPosicion leida: x={}, y={}, z={}".format(p.x, p.y, p.z))
    print("Orientacion leida: w={}, x={}, y={}, z={}".format(q.w, q.x, q.y, q.z))

# Declaración del suscriptor
topic = 'topic_pose'
pub = rospy.Subscriber(topic, Pose, callback_func)

# Mantener el nodo activo (hasta que se detenga
rospy.spin()

