#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import rospy
from sensor_msgs.msg import Joy


# Inicializar el nodo
rospy.init_node('nodo_suscriptor_joy')

# Función de callback
def callback_func(msg):
    print("\nTiempo: " + str(msg.header.stamp))
    print("Frame leido: " + msg.header.frame_id)
    print("Ejes leidos: ")
    axes = msg.axes
    for i in range(len(axes)):
        print(str(axes[i]))

# Declaración del suscriptor
topic = 'topic_joy'
pub = rospy.Subscriber(topic, Joy, callback_func)

# Mantener el nodo activo (hasta que se detenga
rospy.spin()

